apiVersion: batch/v1
kind: Job
metadata:
  name:  search-migrate
spec:
  template:
    spec:
      containers:
      - name: search-migrate
        image: public.ecr.aws/l4v6k6q7/548aa238cf557a6669a82a3579832051_search_migrations:latest
        env:
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: search-database-connection-string
              key: database_url
      restartPolicy: Never