apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: search
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: projects
        image: public.ecr.aws/l4v6k6q7/9c3de1338c9f1c8647ddd2fb7dd32856_search:latest
        ports:
        - containerPort: 80