apiVersion: v1
kind: Service
metadata:
  name: search-postgres
  labels:
    app: search-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: search-postgres