apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-postgres-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: search-postgres-volume