apiVersion: v1
kind: PersistentVolume
metadata:
  name: search-postgres-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /home/c/search_postgres